services:
  - type: web
    name: tg-parser-bot
    runtime: python
    plan: free
    buildCommand: pip install -r tg_parser_requirements.txt
    startCommand: python tg_parser_bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: REQUIRED_CHANNEL
        sync: false
